//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotFramework.Infra.Logging.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotFramework.Infra.Logging.Configuration.DesignResources", typeof(DesignResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A logging target listener that sends log messages to logger service..
        /// </summary>
        internal static string LoggerServiceTraceListenerDescription {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Listener.
        /// </summary>
        internal static string LoggerServiceTraceListenerDisplayName {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum severity of messages that will be sent to the logging target. 
        ///Valid values are All (the default), Off, Critical, Error, Warning, Information, Verbose, and Activity Tracing. 
        ///The behavior is for messages with the selected severity and all higher severities to be included. 
        ///For example, the Warning setting will allow warning, error, and critical messages to be written to the logging target..
        /// </summary>
        internal static string LoggerServiceTraceListenerFilterDescription {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity Filter.
        /// </summary>
        internal static string LoggerServiceTraceListenerFilterDisplayName {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerFilterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Log Message Formatter to use to format log messages written to the logger service..
        /// </summary>
        internal static string LoggerServiceTraceListenerFormatterDescription {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerFormatterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatter.
        /// </summary>
        internal static string LoggerServiceTraceListenerFormatterDisplayName {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerFormatterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Listener..
        /// </summary>
        internal static string LoggerServiceTraceListenerListenerDataTypeNameDescription {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerListenerDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener Data Type.
        /// </summary>
        internal static string LoggerServiceTraceListenerListenerDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerListenerDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Trace Listener..
        /// </summary>
        internal static string LoggerServiceTraceListenerNameDescription {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LoggerServiceTraceListenerNameDisplayName {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeners that do not output to a Text Formatter use this property to determine which options, or elements, should be included in the trace output. 
        ///Possible values are: CallStack, DateTime, LogicalOperationStack, None, ProcessId, ThreadId, and Timestamp. The default is None. This property is optional..
        /// </summary>
        internal static string LoggerServiceTraceListenerTraceOutputOptionsDescription {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerTraceOutputOptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Output Options.
        /// </summary>
        internal static string LoggerServiceTraceListenerTraceOutputOptionsDisplayName {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerTraceOutputOptionsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Database Trace Listener..
        /// </summary>
        internal static string LoggerServiceTraceListenerTypeNameDescription {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string LoggerServiceTraceListenerTypeNameDisplayName {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address of endpoint in logger service that writes log messages. 
        ///The default is &apos;WriteLog&apos;, and is created by the scripts you can run to create the logging database..
        /// </summary>
        internal static string LoggerServiceTraceListenerWriteLogEndpointAddressDescription {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerWriteLogEndpointAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write To Log Endpoint Address.
        /// </summary>
        internal static string LoggerServiceTraceListenerWriteLogEndpointAddressDisplayName {
            get {
                return ResourceManager.GetString("LoggerServiceTraceListenerWriteLogEndpointAddressDisplayName", resourceCulture);
            }
        }
    }
}
